# Workflow name
name: App release

# When it will be triggered
on:
  push:
    branches:
      - main

# Where it will run
jobs:
  build:
    permissions:
      packages: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
          cache-dependency-path: |
            ${{ github.workspace }}/gradle/wrapper/gradle-wrapper.properties
            ${{ github.workspace }}/**/*.gradle*

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Restore playstore.keystore.jks
        run: echo ${{secrets.KEYSTORE_FILE}} | base64 -d > ${GITHUB_WORKSPACE}/keystore.jks

      - name: Add keystore information to local.properties
        run: echo "signing.default.file=${GITHUB_WORKSPACE}/keystore.jks" >> local.properties

      - name: Add keystore password to local.properties
        run: echo "signing.default.storepassword=${{secrets.KEYSTORE_PASSWORD}}" >> local.properties

      - name: Add keystore alias to local.properties
        run: echo "signing.default.keyalias=key0" >> local.properties

      - name: Add keystore key password to local.properties
        run: echo "signing.default.keypassword=${{secrets.KEYSTORE_PASSWORD}}" >> local.properties

      # Build the app
      - name: Build the app
        run: ./gradlew assembleRelease

      # Export APK
      - name: Export APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: DVBerry
          path: app/build/outputs/apk/release/app-release.apk
          compression-level: 0
          if-no-files-found: error

      - name: Set date
        run: echo "DATE=$(date '+%d.%m.%Y %H:%M')" >> $GITHUB_ENV
      - name: Set date for tag name
        run: echo "TAG_DATE=$(date '+%Y%m%d_%H-%M')" >> $GITHUB_ENV
      # Create release
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
          draft: false
          prerelease: false
          make_latest: true
          name: DVBerry (${{ env.DATE }})
          fail_on_unmatched_files: true
          tag_name: v${{ env.TAG_DATE }}