# Workflow name
name: App release

# When it will be triggered
on:
  push:
    branches:
      - 7-ci-signing

# Where it will run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Restore playstore.keystore.jks
        run: echo $KEYSTORE_FILE | base64 -d > keystore.jks

      - name: Add keystore information to local.properties
        run: echo "signing.default.file=keystore.jks" >> local.properties

      - name: Add keystore password to local.properties
        run: echo "signing.default.storepassword=$KEYSTORE_PASSWORD" >> local.properties

      - name: Add keystore alias to local.properties
        run: echo "signing.default.keyalias=key0" >> local.properties

      - name: Add keystore key password to local.properties
        run: echo "signing.default.keypassword=$KEYSTORE_KEY_PASSWORD" >> local.properties

      # Build the app
      - name: Build the app
        run: ./gradlew assembleRelease

      # Export APK
      - name: Export APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk