name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  verify-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-project
        name: Setup Project
        with:
          keystore_file: ${{ secrets.KEYSTORE_FILE }}
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Build Debug APK
        run: ./gradlew assembleDebug